name: Build and Deploy to k8s

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the v3 branch
  push:
    branches: [ v3 ]
  workflow_dispatch:
jobs:
  build:
    runs-on: xentrail

    steps:

      - name: Run a one-line script
        run: cat /etc/hosts

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
