name: Build and Deploy to k8s
env:
  SERVER: production

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the v3 branch
  push:
    branches: [ v3 ]
  workflow_dispatch:
jobs:
  build:
    runs-on: xentrail

    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: cat src/app.py

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          sudo docker build -t xentrail:v3 .
          echo test, and deploy your project.
  push:
    runs-on: xentrail
    steps:
      - name: push to ECR
        run: echo ${SERVER}
    
